name: flick_video_player
description: Flick Video Player is a video player for flutter. The video_player plugin gives low level access for the video playback.
repository: https://github.com/GeekyAnts/flick-video-player
homepage: https://github.com/GeekyAnts/flick-video-player

version: 0.1.1

environment:
  sdk: ">=2.11.0 <3.0.0"
  flutter: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Custom video player with custom loadControl for exoplayer
  video_player: #2.4.6 fr/buffer_controls
    git:
      url: https://github.com/frontrow-tech/plugins.git
      path: packages/video_player/video_player
      ref: 4fd6ae5d0d886b79497f33a41dad32a487ee58f7
  provider: ^6.0.3
  wakelock: ^0.6.2
  # For passing flags to the underlying Android window manager
  flutter_windowmanager: ^0.2.0
  subtitle_wrapper_package:
    git:
      url: https://github.com/frontrow-tech/flutter_subtitle_wrapper.git
      ref: db54cd40644c16a9e9240f8eddc467349ceb12b8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
